### PR TITLE
Updated version and rerendered with the latest conda-smithy

### PR DESCRIPTION
**Pull request by ghost**
Signed-off-by: Alex Johnson <hello@alex-johnson.net>

### CODE REVIEW

**Comment by nicoddemus** [comment]
Thanks @TheOriginalAlex!

**Comment by nicoddemus** [comment]
@conda-forge-admin, please add noarch: python

**Comment by nicoddemus** [comment]
Hmmm strange, no idea why the `noarch` build failed.

Well I'm reverting my commits then, sorry for the noise.

**Comment by isuruf** [comment]
@nicoddemus, see https://github.com/conda/conda-build/issues/2362

**Comment by nicoddemus** [comment]
Thanks @isuruf for the link.

**Pull request merged**
