### PR TITLE
Update package to v2

### PR DESCRIPTION
**Pull request by setu4993**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Updates the package to v2. Supercedes #26.

### CODE REVIEW

**Comment by setu4993** [comment]
@conda-forge-admin, please rerender

**Comment by setu4993** [comment]
@nicoddemus : Can you please help review? I can help maintain this package thereafter.

**Review by nicoddemus — APPROVED** [review]
Thanks!

**Comment by setu4993** [comment]
Nice catch on https://github.com/conda-forge/invoke-feedstock/pull/27/commits/5558f3dbba1a34b4c78b87b1014a5bd6f766c409. Thanks @nicoddemus!

**Pull request merged**
